version: '3'

volumes:
  postgres_data: {}

services:
  api:
    build:
      context: ./backend
      dockerfile: ../compose/production/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: ./compose/production/.env
  
  frontend:
    build:
      context: ./frontend
      dockerfile: ../compose/production/node/Dockerfile
    command: npm run serve
    volumes:
      - ./compose/production/.env:/app/.env:ro
      - ./frontend:/app
    ports:
      - "8080:8080"
    working_dir: /app
    restart: on-failure

  postgres:
    build: ./compose/production/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: ./compose/production/.env

  nginx:
    build:
      context: ./
      dockerfile: ./compose/production/nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - api
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./compose/production/nginx/nginx.conf:/etc/nginx/nginx.conf:ro