version: '3'

volumes:
  postgres_data: {}

services:
  api:
    build:
      context: ./backend
      dockerfile: ../compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: ./compose/local/.env
  
  frontend:
    build:
      context: ./frontend
      dockerfile: ../compose/local/node/Dockerfile
    command: /bin/bash -c "npm i && npm run serve"
    volumes:
      - ./compose/local/.env:/app/.env:ro
      - ./frontend:/app
    ports:
      - "8080:8080"
    working_dir: /app
    restart: on-failure

  postgres:
    build: ./compose/local/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: ./compose/local/.env