version: '3'

volumes:
  postgres_data: {}

services:
  api:
    build:
      context: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env
  
  frontend:
    image: node:10
    command: /bin/bash -c "npm i && npm run serve"
    volumes:
      - ./.env:/app/.env:ro
      - ./frontend:/app
    ports:
      - "8080:8080"
    working_dir: /app
    restart: on-failure

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env